name: 'Terraform'

on:
  push:
    branches: [ main ]
      
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET}}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{ secrets.AZURE_SP_TENANT_ID }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Install pre-reqs'
        run: |
          curl -SL "https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip" --output terraform.zip
          unzip "terraform.zip"
          mv terraform /usr/local/bin
          terraform --version
          rm terraform.zip   
      - name: 'Install TFLint'
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.45.0/tflint_linux_amd64.zip
          unzip tflint_linux_amd64
          mv tflint /usr/local/bin

      - name: Terraform Init
        run: terraform init

   