name: 'Terraform'

on: 
  push:
    branches: [ main ]
     

jobs:
  terraform:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    
    
#defaults:
 # run:
  #  shell: bash
   # working-directory: terraform

  steps:
    - uses: actions/checkout@v3
    - name: 'Install pre-reqs'
        run: |
        curl -SL "https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip" --output terraform.zip
        unzip "terraform.zip"
        mv terraform /usr/local/bin
        terraform --version
        rm terraform.zip

    - name: 'Install TFLint'
        run: |
        wget https://github.com/terraform-linters/tflint/releases/tflint_linux_amd64.zip
        unzip tflint_linux_amd64.zip
        mv tflint /usr/local/bin